Repository wireapp/wire-server, pull requests merged in 2022-08, with the labels that each got.

#2526 [SQSERVICES-1067] Address user account consistency issue when SCIM provisioning crashes
  changelog.d/5-internal/user-provisioning-resilience
  libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
  libs/wire-api/src/Wire/API/User.hs
  libs/wire-api/src/Wire/API/User/RichInfo.hs
  libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/NewUserPublic_user.hs
  services/brig/src/Brig/API/Internal.hs
  services/brig/src/Brig/API/Types.hs
  services/brig/src/Brig/API/User.hs
  services/brig/src/Brig/Data/Activation.hs
  services/brig/test/integration/Federation/End2end.hs
  services/spar/src/Spar/App.hs
  services/spar/src/Spar/Intra/Brig.hs
  services/spar/src/Spar/Intra/BrigApp.hs
  services/spar/src/Spar/Scim/User.hs
  services/spar/src/Spar/Sem/BrigAccess.hs
  services/spar/src/Spar/Sem/BrigAccess/Http.hs
  services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
  services/spar/test/Test/Spar/DataSpec.hs
Labels: ok-to-test

#2588 Allow remove splash screen
  changelog.d/3-bug-fixes/allow-remove-splash-screen
  libs/wire-api/src/Wire/API/Team.hs
  libs/wire-api/test/golden/Test/Wire/API/Golden/Generated/Team_team.hs
  libs/wire-api/test/golden/testObject_Event_team_1.json
  libs/wire-api/test/golden/testObject_Event_team_13.json
  libs/wire-api/test/golden/testObject_TeamList_team_1.json
  libs/wire-api/test/golden/testObject_TeamList_team_12.json
  libs/wire-api/test/golden/testObject_TeamList_team_14.json
  libs/wire-api/test/golden/testObject_TeamList_team_15.json
  libs/wire-api/test/golden/testObject_TeamList_team_16.json
  libs/wire-api/test/golden/testObject_TeamList_team_18.json
  libs/wire-api/test/golden/testObject_TeamList_team_19.json
  libs/wire-api/test/golden/testObject_TeamList_team_2.json
  libs/wire-api/test/golden/testObject_TeamList_team_20.json
  libs/wire-api/test/golden/testObject_TeamList_team_3.json
  libs/wire-api/test/golden/testObject_TeamList_team_4.json
  libs/wire-api/test/golden/testObject_TeamList_team_5.json
  libs/wire-api/test/golden/testObject_TeamList_team_6.json
  libs/wire-api/test/golden/testObject_TeamList_team_7.json
  libs/wire-api/test/golden/testObject_TeamList_team_9.json
  libs/wire-api/test/golden/testObject_Team_team_1.json
  libs/wire-api/test/golden/testObject_Team_team_10.json
  libs/wire-api/test/golden/testObject_Team_team_11.json
  libs/wire-api/test/golden/testObject_Team_team_12.json
  libs/wire-api/test/golden/testObject_Team_team_13.json
  libs/wire-api/test/golden/testObject_Team_team_14.json
  libs/wire-api/test/golden/testObject_Team_team_15.json
  libs/wire-api/test/golden/testObject_Team_team_16.json
  libs/wire-api/test/golden/testObject_Team_team_17.json
  libs/wire-api/test/golden/testObject_Team_team_18.json
  libs/wire-api/test/golden/testObject_Team_team_19.json
  libs/wire-api/test/golden/testObject_Team_team_2.json
  libs/wire-api/test/golden/testObject_Team_team_20.json
  libs/wire-api/test/golden/testObject_Team_team_3.json
  libs/wire-api/test/golden/testObject_Team_team_4.json
  libs/wire-api/test/golden/testObject_Team_team_5.json
  libs/wire-api/test/golden/testObject_Team_team_6.json
  libs/wire-api/test/golden/testObject_Team_team_7.json
  libs/wire-api/test/golden/testObject_Team_team_8.json
  libs/wire-api/test/golden/testObject_Team_team_9.json
  services/galley/src/Galley/Cassandra/Queries.hs
  services/galley/src/Galley/Cassandra/Team.hs
  services/galley/test/integration/API/Teams.hs
Labels: ok-to-test

#2593 Drop a Deprecated Conversation Member Removal Endpoint
  changelog.d/1-api-changes/deprecated-member-removal
  libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
  services/galley/test/integration/API.hs
  services/galley/test/integration/API/MLS.hs
  services/galley/test/integration/API/Roles.hs
  services/galley/test/integration/API/Teams.hs
  services/galley/test/integration/API/Teams/LegalHold.hs
  services/galley/test/integration/API/Util.hs
Labels: ok-to-test

#2580 SQCORE-1166: Port Brig SearchAPI and UserRichInfo endpoints to Servant (CI copy)
  changelog.d/5-internal/more-brig-api
  libs/wire-api/src/Wire/API/Error/Brig.hs
  libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
  libs/wire-api/src/Wire/API/Team/Role.hs
  libs/wire-api/src/Wire/API/User/RichInfo.hs
  libs/wire-api/src/Wire/API/User/Search.hs
  services/brig/src/Brig/API/Error.hs
  services/brig/src/Brig/API/Public.hs
  services/brig/src/Brig/User/API/Search.hs
Labels: ok-to-test

#2595 docs: update links to helm chart values
  docs/src/how-to/install/includes/helm_dns-ingress-troubleshooting.inc.rst
  docs/src/how-to/install/troubleshooting.rst
  docs/src/understand/helm.rst
Labels: ok-to-test

#2594 docs: merge nix code into toplevel
  .github/workflows/ci.yml
  docs/.dockerignore
  docs/.envrc
  docs/.github/PULL_REQUEST_TEMPLATE.md
  docs/.github/workflows/ci.yml
  docs/Dockerfile
  docs/Makefile
  docs/README.md
  docs/ci/compile-and-upload.yml
  docs/ci/pr.yml
  docs/nix/default.nix
  docs/nix/nixpkgs.nix
  docs/nix/overlay.nix
  docs/nix/python/arabic-reshaper.nix
  docs/nix/python/python-bidi.nix
  docs/nix/python/svglib.nix
  docs/nix/sources.json
  docs/nix/sources.nix
  docs/src/conf.py
  nix/default.nix
  nix/overlay-docs.nix
  nix/pkgs/python-docs/rst2pdf.nix
  nix/pkgs/python-docs/sphinx-multiversion.nix
  nix/pkgs/python-docs/sphinxcontrib-kroki.nix
  nix/pkgs/python-docs/svg2rlg.nix
  nix/sources.json
Labels: ok-to-test

#2592 Updated Schema Profuctor readme with another example
  libs/schema-profunctor/README.md
Labels: ok-to-test

#2598 build/ubuntu/Dockerfile.prebuiler: Enable exe flag when installing cabal-plan
  build/ubuntu/Dockerfile.prebuilder
Labels: not-ok-to-test

#2565 Sqservices 1533 be give saml id ps human readable names in tm
  cassandra-schema.cql
  changelog.d/2-features/pr-2565
  libs/wire-api/src/Wire/API/Routes/Public/Spar.hs
  libs/wire-api/src/Wire/API/User/IdentityProvider.hs
  services/spar/schema/src/Main.hs
  services/spar/schema/src/V16.hs
  services/spar/spar.cabal
  services/spar/src/Spar/API.hs
  services/spar/src/Spar/Data.hs
  services/spar/src/Spar/Sem/IdPConfigStore.hs
  services/spar/src/Spar/Sem/IdPConfigStore/Cassandra.hs
  services/spar/src/Spar/Sem/IdPConfigStore/Mem.hs
  services/spar/test-integration/Test/Spar/APISpec.hs
  services/spar/test-integration/Test/Spar/DataSpec.hs
  services/spar/test-integration/Util/Core.hs
  services/spar/test/Arbitrary.hs
Labels: ok-to-test

#2599 Fix message signature verification
  changelog.d/6-federation/message-tbs
  libs/wire-api/src/Wire/API/MLS/Message.hs
  libs/wire-api/test/resources/external_proposal.mls
  libs/wire-api/test/unit/Test/Wire/API/MLS.hs
  services/galley/src/Galley/API/MLS/Message.hs
Labels: ok-to-test

#2528 Remove AES128 TLS ciphers for TLS 1.2 by default
  changelog.d/2-features/tls-certs-reduce-default-list
  charts/backoffice/templates/configmap.yaml
  charts/cannon/templates/conf/_nginx.conf.tpl
  charts/cannon/values.yaml
  charts/nginx-ingress-controller/values.yaml
  docs/src/how-to/install/tls.rst
  services/federator/src/Federator/Remote.hs
Labels: ok-to-test

#2601 Add cabal-fmt
  Makefile
  changelog.d/5-internal/cabal-fmt
  hack/bin/cabal-fmt.sh
  nix/default.nix
Labels: ok-to-test

#2603 Reformat all cabal files with cabal-fmt
  libs/api-bot/api-bot.cabal
  libs/api-client/api-client.cabal
  libs/bilge/bilge.cabal
  libs/brig-types/brig-types.cabal
  libs/cargohold-types/cargohold-types.cabal
  libs/cassandra-util/cassandra-util.cabal
  libs/deriving-swagger2/deriving-swagger2.cabal
  libs/dns-util/dns-util.cabal
  libs/extended/extended.cabal
  libs/galley-types/galley-types.cabal
  libs/gundeck-types/gundeck-types.cabal
  libs/hscim/hscim.cabal
  libs/imports/imports.cabal
  libs/metrics-core/metrics-core.cabal
  libs/metrics-wai/metrics-wai.cabal
  libs/polysemy-wire-zoo/polysemy-wire-zoo.cabal
  libs/ropes/ropes.cabal
  libs/schema-profunctor/schema-profunctor.cabal
  libs/sodium-crypto-sign/sodium-crypto-sign.cabal
  libs/ssl-util/ssl-util.cabal
  libs/tasty-cannon/tasty-cannon.cabal
  libs/types-common-aws/types-common-aws.cabal
  libs/types-common-journal/types-common-journal.cabal
  libs/types-common/types-common.cabal
  libs/wai-utilities/wai-utilities.cabal
  libs/wire-api-federation/test/Main.hs
  libs/wire-api-federation/wire-api-federation.cabal
  libs/wire-api/wire-api.cabal
  libs/wire-message-proto-lens/wire-message-proto-lens.cabal
  libs/zauth/zauth.cabal
  services/brig/brig.cabal
  services/cannon/cannon.cabal
  services/cargohold/cargohold.cabal
  services/federator/federator.cabal
  services/galley/galley.cabal
  services/gundeck/gundeck.cabal
  services/proxy/proxy.cabal
  services/spar/schema/exe/spar-schema.hs
  services/spar/schema/src/Run.hs
  services/spar/spar.cabal
  services/spar/test-integration/Main.hs
  tools/api-simulations/api-simulations.cabal
  tools/bonanza/bonanza.cabal
  tools/db/assets/assets.cabal
  tools/db/auto-whitelist/auto-whitelist.cabal
  tools/db/billing-team-member-backfill/billing-team-member-backfill.cabal
  tools/db/find-undead/find-undead.cabal
  tools/db/migrate-sso-feature-flag/migrate-sso-feature-flag.cabal
  tools/db/move-team/move-team.cabal
  tools/db/repair-handles/repair-handles.cabal
  tools/db/service-backfill/service-backfill.cabal
  tools/makedeb/makedeb.cabal
  tools/rex/rex.cabal
  tools/stern/stern.cabal
Labels: ok-to-test

#2604 update clients' key package refs upon committing
  changelog.d/5-internal/update-key-package-ref
  libs/wire-api/src/Wire/API/MLS/Commit.hs
  libs/wire-api/src/Wire/API/MLS/KeyPackage.hs
  libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
  services/brig/src/Brig/API/Internal.hs
  services/brig/src/Brig/Data/MLS/KeyPackage.hs
  services/galley/src/Galley/API/MLS/Message.hs
  services/galley/src/Galley/Effects/BrigAccess.hs
  services/galley/src/Galley/Intra/Client.hs
  services/galley/src/Galley/Intra/Effects.hs
Labels: ok-to-test

#2609 Tweak nix env, cabal-fmt
  changelog.d/5-internal/2609-tweak-stuff
  hack/bin/cabal-fmt.sh
  nix/default.nix
Labels: ok-to-test

#2610 backoffice: allow overriding host to ibis/galeb, and set defaults mat…
  changelog.d/3-bug-fixes/backoffice-ibis
  charts/backoffice/templates/configmap.yaml
  charts/backoffice/values.yaml
Labels: ok-to-test

#2575 Allow features to be set with HTTP method PATCH (SQPIT-1142)
  changelog.d/5-internal/allow-patch-method-for-feature-setting
  libs/wire-api/src/Wire/API/MLS/CipherSuite.hs
  services/galley/src/Galley/API/Internal.hs
  services/galley/test/integration/API/Teams/Feature.hs
  services/galley/test/integration/API/Util/TeamFeature.hs
Labels: ok-to-test

#2611 Use rust image to build mls-test-cli
  build/ubuntu/Dockerfile.deps
Labels: ok-to-test

#2608 replace the release notes with a page pointing to github release note…
  docs/src/release-notes.rst
Labels: ok-to-test

#2605 SQSERVICES-1388-email-localization-when-provisioning-users-with-scim-2
  changelog.d/2-features/pr-2605
  libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
  libs/wire-api/src/Wire/API/User.hs
  services/brig/src/Brig/API/Internal.hs
  services/spar/spar.cabal
  services/spar/src/Spar/App.hs
  services/spar/src/Spar/Intra/Brig.hs
  services/spar/src/Spar/Scim/User.hs
  services/spar/src/Spar/Sem/BrigAccess.hs
  services/spar/src/Spar/Sem/BrigAccess/Http.hs
  services/spar/test-integration/Test/Spar/Scim/UserSpec.hs
  services/spar/test-integration/Util/Scim.hs
Labels: ok-to-test

#2612 Bump mls-test-cli
  libs/metrics-core/src/Data/Metrics.hs
  libs/wire-api/src/Wire/API/Asset.hs
  libs/wire-api/src/Wire/API/Error.hs
  libs/wire-api/src/Wire/API/Routes/MultiVerb.hs
  libs/wire-api/src/Wire/API/Routes/Named.hs
  libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
  libs/wire-api/src/Wire/API/Routes/Public/Galley.hs
  libs/wire-api/src/Wire/API/Routes/Public/Util.hs
  libs/wire-api/test/golden/Test/Wire/API/Golden/Manual/ConversationCoverView.hs
  nix/default.nix
  nix/overlay-docs.nix
  nix/pkgs/mls_test_cli/default.nix
  nix/sources.json
  nix/sources.nix
  services/brig/src/Brig/Data/Activation.hs
  services/brig/src/Brig/Data/Client.hs
  services/brig/src/Brig/User/Auth/Cookie.hs
  services/brig/test/integration/API/Team.hs
  services/brig/test/integration/API/User/Account.hs
  services/gundeck/test/unit/DelayQueue.hs
  tools/api-simulations/smoketest/src/Network/Wire/Simulations/SmokeTest.hs
Labels: ok-to-test

#2621 Add build instructions for developers
  .gitignore
  Makefile
  README.md
  changelog.d/5-internal/building-docs
  docs/developer/building.md
  hie.yaml
  tools/convert-to-cabal/README.md
Labels: ok-to-test, not-ok-to-test

#2626 Add mls-test-cli to builder image
  build/ubuntu/Dockerfile.builder
  build/ubuntu/Dockerfile.deps
  changelog.d/5-internal/ml-test-cli-builder-image
Labels: ok-to-test, not-ok-to-test

#2630 Add mls-test-cli to deps image
  build/ubuntu/Dockerfile.deps
  changelog.d/5-internal/mls-test-cli-deps-image
Labels: not-ok-to-test

#2629 Fix broken hls-hlint-plugin in nix env
  changelog.d/5-internal/hls-hlint-plugin-workaround
  nix/sources.json
Labels: not-ok-to-test

#2624 apply cabal-fmt
  changelog.d/5-internal/apply-cabal-fmt
  libs/dns-util/dns-util.cabal
  libs/extended/extended.cabal
  libs/hscim/hscim.cabal
  libs/metrics-wai/metrics-wai.cabal
  libs/sodium-crypto-sign/sodium-crypto-sign.cabal
  libs/types-common-journal/types-common-journal.cabal
  libs/wire-api-federation/wire-api-federation.cabal
  libs/wire-message-proto-lens/wire-message-proto-lens.cabal
  services/spar/spar.cabal
Labels: ok-to-test

#2632 print mls-test-cli Git revision when building Docker image
  build/ubuntu/Dockerfile.builder
  build/ubuntu/Dockerfile.deps
Labels: ok-to-test

#2634 mls-test-cli - use Cargo.lock
  build/ubuntu/Dockerfile.builder
  build/ubuntu/Dockerfile.deps
  changelog.d/5-internal/mls-test-cli-lock-file
Labels: not-ok-to-test

#2567 Add support for MLS External Add Proposals
  changelog.d/5-internal/FS-435
  nix/pkgs/mls_test_cli/default.nix
  services/galley/src/Galley/API/MLS/Message.hs
  services/galley/test/integration/API/MLS.hs
  services/galley/test/integration/API/MLS/Util.hs
Labels: ok-to-test

#2635 apply linter suggestions
  services/galley/src/Galley/API/MLS/Message.hs
Labels: ok-to-test

#2623 Sanitize `delete-cache-on-linker-errors` make target
  Makefile
  changelog.d/5-internal/cleanup-caches-make-target
Labels: ok-to-test

#2586 Typos etc.
  changelog.d/5-internal/typos-etc
  docs/legacy/reference/user/registration.md
  libs/galley-types/src/Galley/Types/Teams.hs
  libs/wire-api/src/Wire/API/Team/Feature.hs
  libs/wire-api/src/Wire/API/Team/SearchVisibility.hs
  services/galley/src/Galley/API/Teams/Features.hs
Labels: ok-to-test

#2597 Serialisation of remove proposals
  libs/wire-api/src/Wire/API/MLS/Commit.hs
  libs/wire-api/src/Wire/API/MLS/Epoch.hs
  libs/wire-api/src/Wire/API/MLS/Group.hs
  libs/wire-api/src/Wire/API/MLS/KeyPackage.hs
  libs/wire-api/src/Wire/API/MLS/Message.hs
  libs/wire-api/src/Wire/API/MLS/Proposal.hs
  libs/wire-api/src/Wire/API/MLS/Serialisation.hs
  libs/wire-api/test/unit/Main.hs
  libs/wire-api/test/unit/Test/Wire/API/MLS.hs
  libs/wire-api/test/unit/Test/Wire/API/Roundtrip/MLS.hs
  libs/wire-api/wire-api.cabal
  nix/pkgs/mls_test_cli/default.nix
Labels: ok-to-test

#2633 SQSERVICES-1645-backend-servantify-brig-auth-api
  changelog.d/5-internal/pr-2633
  libs/wire-api/src/Wire/API/User/Auth.hs
  libs/wire-api/src/Wire/API/User/Auth2.hs
  libs/wire-api/test/unit/Main.hs
  libs/wire-api/test/unit/Test/Wire/API/User/Auth.hs
  libs/wire-api/wire-api.cabal
Labels: ok-to-test

#2642 Make mlsPrivateKeys value optional
  charts/galley/templates/configmap.yaml
  charts/galley/templates/mls-secret.yaml
Labels: ok-to-test

#2639 We only need one rule for `make clean`.
  Makefile
  changelog.d/5-internal/tweak-makefile
  docs/developer/building.md
Labels: ok-to-test

#2617 port checklist documentation over to docs, and adjust PR template
  .github/pull_request_template.md
  changelog.d/5-internal/internal-PR-template-processes
  docs/legacy/developer/adding-api-endpoints.md
  docs/legacy/developer/adding-config-options.md
Labels: ok-to-test

#2643 charts/galley: Set secrets to empty object
  charts/galley/values.yaml
Labels: ok-to-test

#2640 Fix cql-io bug where restarting C* cluster could cause downtime
  cabal.project
  cabal.project.freeze
  changelog.d/3-bug-fixes/cql-io-control
  stack.yaml
Labels: ok-to-test

#2647 added information on finding and deleting users that are not part of …
  docs/src/how-to/administrate/users.rst
Labels: ok-to-test

#2625 smoketest/loadtest documentation snippet
  tools/api-simulations/README.md
Labels: ok-to-test

#2641 Sqservices 1721 acme be new nonce endpoint
  cassandra-schema.cql
  changelog.d/2-features/pr-2641
  charts/brig/templates/configmap.yaml
  charts/brig/values.yaml
  charts/nginz/values.yaml
  deploy/services-demo/conf/brig.demo-docker.yaml
  deploy/services-demo/conf/brig.demo.yaml
  deploy/services-demo/conf/nginz/nginx.conf
  docs/src/how-to/install/team-feature-settings.md
  hack/helm_vars/wire-server/values.yaml.gotmpl
  libs/types-common/src/Data/Nonce.hs
  libs/types-common/test/Test/Properties.hs
  libs/types-common/types-common.cabal
  libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
  services/brig/brig.cabal
  services/brig/brig.integration.yaml
  services/brig/schema/src/Main.hs
  services/brig/schema/src/V72_AddNonceTable.hs
  services/brig/src/Brig/API/Public.hs
  services/brig/src/Brig/App.hs
  services/brig/src/Brig/Data/Nonce.hs
  services/brig/src/Brig/Options.hs
  services/brig/test/integration/API/User/Client.hs
  services/brig/test/integration/API/User/Util.hs
Labels: ok-to-test

#2645 Sqservices 1645 backend servantify brig auth api 2
  changelog.d/5-internal/pr-2633
  libs/wire-api/test/unit/Test/Wire/API/User/Auth.hs
Labels: ok-to-test

#2638 Brig: Remove redundant constraints
  changelog.d/5-internal/brig-redundant-constraints
  services/brig/src/Brig/API/Client.hs
  services/brig/src/Brig/API/Error.hs
  services/brig/src/Brig/API/Public.hs
  services/brig/src/Brig/API/User.hs
  services/brig/src/Brig/AWS.hs
  services/brig/src/Brig/App.hs
  services/brig/src/Brig/Data/Activation.hs
  services/brig/src/Brig/Data/User.hs
  services/brig/src/Brig/Federation/Client.hs
  services/brig/src/Brig/IO/Intra.hs
  services/brig/src/Brig/Index/Eval.hs
  services/brig/src/Brig/Index/Migrations.hs
  services/brig/src/Brig/InternalEvent/Process.hs
  services/brig/src/Brig/Provider/API.hs
  services/brig/src/Brig/Team/DB.hs
  services/brig/src/Brig/User/API/Auth.hs
  services/brig/src/Brig/User/Auth.hs
  services/brig/src/Brig/User/Auth/Cookie.hs
  services/brig/src/Brig/User/Search/Index.hs
Labels: ok-to-test

#2628 [FS-721] Forward All Default Proposals
  changelog.d/2-features/mls-fwd-all-default-proposals
  libs/wire-api/src/Wire/API/MLS/Extension.hs
  libs/wire-api/src/Wire/API/MLS/Proposal.hs
  libs/wire-api/src/Wire/API/MLS/Serialisation.hs
  libs/wire-api/test/unit/Test/Wire/API/Roundtrip/MLS.hs
  services/galley/galley.cabal
  services/galley/src/Galley/API/MLS/Message.hs
  services/galley/test/integration/API/MLS.hs
  services/galley/test/integration/API/MLS/Util.hs
Labels: ok-to-test

#2649 Fixup
  changelog.d/4-docs/publish-developer-docs
  docs/README.original.md
Labels: ok-to-test

#2651 Fix key package error description
  changelog.d/1-api-changes/fix-mls-error-desc
  libs/wire-api/src/Wire/API/Error/Brig.hs
Labels: ok-to-test

#2654 Fix cabal formatting
  libs/polysemy-wire-zoo/polysemy-wire-zoo.cabal
Labels: ok-to-test

#2636 Brig Polysemy: Port UserPendingActivationStore to polysemy
  changelog.d/5-internal/brig-upa-store-effect
  services/brig/brig.cabal
  services/brig/src/Brig/API.hs
  services/brig/src/Brig/API/Internal.hs
  services/brig/src/Brig/API/Public.hs
  services/brig/src/Brig/API/User.hs
  services/brig/src/Brig/CanonicalInterpreter.hs
  services/brig/src/Brig/Data/UserPendingActivation.hs
  services/brig/src/Brig/Run.hs
  services/brig/src/Brig/Sem/UserPendingActivationStore.hs
  services/brig/src/Brig/Sem/UserPendingActivationStore/Cassandra.hs
  services/brig/src/Brig/Team/API.hs
  services/brig/test/integration/Main.hs
Labels: ok-to-test

#2631 Improve MLS client checks
  changelog.d/0-release-notes/get-mls-clients
  changelog.d/3-bug-fixes/improve-client-check
  libs/wire-api-federation/src/Wire/API/Federation/API/Brig.hs
  libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
  libs/wire-api/src/Wire/API/User/Client.hs
  services/brig/src/Brig/API/Federation.hs
  services/brig/src/Brig/API/Internal.hs
  services/brig/test/integration/API/Internal.hs
  services/galley/src/Galley/API/MLS/Message.hs
  services/galley/src/Galley/Effects/BrigAccess.hs
  services/galley/src/Galley/Intra/Client.hs
  services/galley/test/integration/API/MLS.hs
  services/galley/test/integration/API/MLS/Util.hs
Labels: ok-to-test

#2655 Make nonces lookuppable by client ids
  cassandra-schema.cql
  changelog.d/5-internal/fix-nonce-table
  libs/types-common/src/Data/Nonce.hs
  libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
  services/brig/brig.cabal
  services/brig/schema/src/Main.hs
  services/brig/schema/src/V73_ReplaceNonceTable.hs
  services/brig/src/Brig/API/Public.hs
  services/brig/src/Brig/App.hs
  services/brig/src/Brig/Data/Nonce.hs
  services/brig/src/Brig/Options.hs
  services/brig/test/integration/API/User/Client.hs
  services/brig/test/integration/API/User/Util.hs
Labels: ok-to-test

#2659 Update mls-test-cli to 0.4.0
  nix/pkgs/mls_test_cli/default.nix
Labels: ok-to-test

#2656 Run integration tests with delivered Elastic Search version
  changelog.d/5-internal/update_elasticsearch_ephemeral_version
  charts/elasticsearch-ephemeral/values.yaml
Labels: ok-to-test

#2646 Create PR guidelines and simplify checklist
  .github/pull_request_template.md
  docs/src/developer/developer/pr-guidelines.md
Labels: not-ok-to-test
