Repository wireapp/wire-server, pull requests merged in 2025-02, with the labels that each got.

#4418 [WPB-14310] Move domain registration guards to their respective subsystems
  integration/test/Test/Teams.hs
  libs/types-common/src/Data/Domain.hs
  libs/wire-api/src/Wire/API/EnterpriseLogin.hs
  libs/wire-api/src/Wire/API/User/EmailAddress.hs
  libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem.hs
  libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Error.hs
  libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs
  libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Null.hs
  libs/wire-subsystems/src/Wire/InvitationStore.hs
  libs/wire-subsystems/src/Wire/InvitationStore/Cassandra.hs
  libs/wire-subsystems/src/Wire/TeamInvitationSubsystem/Error.hs
  libs/wire-subsystems/src/Wire/TeamInvitationSubsystem/Interpreter.hs
  libs/wire-subsystems/src/Wire/UserSubsystem.hs
  libs/wire-subsystems/src/Wire/UserSubsystem/Error.hs
  libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs
  libs/wire-subsystems/test/unit/Wire/EnterpriseLoginSubsystem/InterpreterSpec.hs
  libs/wire-subsystems/test/unit/Wire/MiniBackend.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/EmailSubsystem.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/EnterpriseLoginSubsystem.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/GalleyAPIAccess.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/InvitationStore.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/TinyLog.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/UserSubsystem.hs
  libs/wire-subsystems/test/unit/Wire/TeamInvitationSubsystem/InterpreterSpec.hs
  libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs
  libs/wire-subsystems/wire-subsystems.cabal
  services/brig/src/Brig/API/Internal.hs
  services/brig/src/Brig/API/Public.hs
Labels: ok-to-test, echoes/initiative: scale

#4436 Save group info within commit lock
  changelog.d/3-bug-fixes/mls-group-info-lock
  integration/test/Test/MLS/SubConversation.hs
  services/galley/src/Galley/API/MLS/Commit/InternalCommit.hs
  services/galley/src/Galley/API/MLS/Message.hs
Labels: ok-to-test, echoes: product-roadmap/bug

#4438 WPB-15801 GET and DELETE Registered Domains
  cassandra-schema.cql
  changelog.d/1-api-changes/WPB-14307
  charts/nginz/values.yaml
  integration/test/API/Brig.hs
  integration/test/Test/DomainVerification.hs
  libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
  libs/wire-api/src/Wire/API/Routes/Public/Brig/DomainVerification.hs
  libs/wire-subsystems/src/Wire/DomainRegistrationStore.hs
  libs/wire-subsystems/src/Wire/DomainRegistrationStore/Cassandra.hs
  libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem.hs
  libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/DomainRegistrationStore.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/EnterpriseLoginSubsystem.hs
  services/brig/brig.cabal
  services/brig/src/Brig/API/Public.hs
  services/brig/src/Brig/Schema/Run.hs
  services/brig/src/Brig/Schema/V90_DomainRegistrationTeamIndex.hs
  services/nginz/integration-test/conf/nginz/nginx.conf
Labels: ok-to-test, echoes/initiative: scale

#4441 WPB-15933 Special case of getDomainRegistrationPublic
  changelog.d/1-api-changes/WPB-15933
  integration/test/Test/DomainVerification.hs
  libs/wire-api/src/Wire/API/Routes/Public/Brig/DomainVerification.hs
  libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem.hs
  libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs
  services/brig/src/Brig/API/Public.hs
Labels: ok-to-test, echoes/initiative: scale

#4443 Test single consumer behaviour of notifications
  changelog.d/5-internal/single-consumer-test
  integration/test/Test/Events.hs
Labels: ok-to-test, echoes/initiative: scale

#4449 Cleanup ingress classes after integration tests.
  changelog.d/5-internal/ingress-classes
  hack/bin/integration-cleanup.sh
  hack/bin/integration-spring-cleaning.sh
  hack/bin/integration-teardown-federation.sh
  hack/bin/integration-teardown-ingress-classes.sh
Labels: ok-to-test

#4448 Replace Sbom and bombon with tom-bombadil flake
  .gitignore
  Makefile
  changelog.d/5-internal/use-tom-bombadil
  hack/bin/Sbom.hs
  hack/bin/bombon.hs
  nix/all-toplevel-derivations.nix
  nix/pkg-info.nix
  nix/wire-server.nix
Labels: ok-to-test

#4450 Fix helmfile destroy that was missing an env variable
  changelog.d/5-internal/helmfile-destroy
  hack/bin/integration-teardown-federation.sh
Labels: ok-to-test

#4452 WPB-14310 Implement checks for domain registration
  changelog.d/2-features/domain-registration-blocks
  integration/integration.cabal
  integration/test/API/Brig.hs
  integration/test/API/Common.hs
  integration/test/SetupHelpers.hs
  integration/test/Test/DomainVerification.hs
  integration/test/Test/Register.hs
  integration/test/Test/Spar/STM.hs
  integration/test/Test/Teams.hs
  integration/test/Test/User.hs
  libs/wire-api/src/Wire/API/User/IdentityProvider.hs
  libs/wire-subsystems/default.nix
  libs/wire-subsystems/src/Wire/InvitationStore.hs
  libs/wire-subsystems/src/Wire/TeamInvitationSubsystem.hs
  libs/wire-subsystems/src/Wire/UserSubsystem.hs
  libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs
  libs/wire-subsystems/test/unit/Wire/EnterpriseLoginSubsystem/InterpreterSpec.hs
  libs/wire-subsystems/test/unit/Wire/MiniBackend.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/GalleyAPIAccess.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/IndexedUserStore.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/SparAPIAccess.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/UserSubsystem.hs
  libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs
  libs/wire-subsystems/wire-subsystems.cabal
  services/brig/src/Brig/API/Auth.hs
  services/brig/src/Brig/API/Internal.hs
  services/brig/src/Brig/API/Public.hs
  services/brig/src/Brig/API/User.hs
  services/spar/test/Arbitrary.hs
Labels: ok-to-test

#4440 Upgrade to later redis chart with an image containing fewer CVEs
  changelog.d/5-internal/upgrade-redis
  charts/cannon/values.yaml
  charts/gundeck/values.yaml
  charts/redis-ephemeral/requirements.yaml
  charts/redis-ephemeral/templates/helpers.tpl
  charts/redis-ephemeral/values.yaml
  hack/helm_vars/certs/values.yaml.gotmpl
  hack/helm_vars/wire-server/values.yaml.gotmpl
  hack/helmfile.yaml
Labels: ok-to-test

#4455 WPB-16141 Enforce no activation if email domain is registered for another team or backend
  changelog.d/2-features/WPB-16141
  integration/test/Test/User.hs
  libs/wire-subsystems/src/Wire/UserSubsystem.hs
  libs/wire-subsystems/src/Wire/UserSubsystem/Interpreter.hs
  libs/wire-subsystems/test/unit/Wire/MockInterpreters/UserSubsystem.hs
  libs/wire-subsystems/test/unit/Wire/UserSubsystem/InterpreterSpec.hs
  services/brig/src/Brig/API/Public.hs
  services/brig/src/Brig/API/User.hs
  services/brig/src/Brig/Data/Activation.hs
Labels: ok-to-test

#4457 feat: Alpine version bump to v3.21.3 for cassandra-migrations and cannon helm charts
  changelog.d/5-internal/alpine-version
  charts/cannon/templates/statefulset.yaml
  charts/cassandra-migrations/templates/migrate-schema.yaml
Labels: ok-to-test

#4460 create CODEOWNERS file
  CODEOWNERS
Labels: ok-to-test

#4461 Add backend team to all subdirs in CODEOWNERS
  CODEOWNERS
Labels: ok-to-test

#4463 feat(fake-aws-sqs): softwaremill/elasticmq-native image version bump to 1.6.11
  changelog.d/5-internal/update-fake-aws-sqs-elasticmq-native
  charts/fake-aws-sqs/values.yaml
Labels: ok-to-test

#4462 feat(reaper) bump bitnami/kubectl docker image from 1.24.12 to 1.32.2
  changelog.d/5-internal/update-kubectl-image-reaper-helm-chart
  charts/reaper/templates/deployment.yaml
Labels: ok-to-test

#4465 WPB-16210 Allow transitioning from `no-registration` to `backend` configuration for email domain registration
  changelog.d/3-bug-fixes/W-16210
  integration/test/Test/DomainVerification.hs
  libs/wire-subsystems/src/Wire/EnterpriseLoginSubsystem/Interpreter.hs
Labels: ok-to-test

#4416 WPB-15480: fix(sftd_disco): update base image to fix CVEs
  changelog.d/3-bug-fixes/WPB-15480
  tools/sftd_disco/Dockerfile
  tools/sftd_disco/Makefile
Labels: ok-to-test, echoes: technical-roadmap/security

#4466 WPB-16142 Do not require email verification for SSO created accounts if the domain is registered for that team
  changelog.d/2-features/WPB-16142
  integration/test/API/BrigInternal.hs
  integration/test/SetupHelpers.hs
  integration/test/Test/DomainVerification.hs
  integration/test/Test/Spar.hs
  integration/test/Test/Spar/STM.hs
  libs/wire-api/src/Wire/API/Routes/Internal/Brig.hs
  libs/wire-api/src/Wire/API/Routes/Public/Brig.hs
  libs/wire-api/src/Wire/API/Routes/Public/Brig/DomainVerification.hs
  libs/wire-api/src/Wire/API/User.hs
  libs/wire-subsystems/src/Wire/UserSubsystem.hs
  services/brig/src/Brig/API/Internal.hs
  services/brig/src/Brig/API/User.hs
  services/brig/src/Brig/Data/Activation.hs
  services/spar/src/Spar/App.hs
  services/spar/test-integration/Util/Email.hs
Labels: ok-to-test

#4472 Team feature migration tool
  cabal.project
  changelog.d/0-release-notes/simplify-feature-table
  nix/local-haskell-packages.nix
  nix/wire-server.nix
  services/galley/default.nix
  services/galley/galley.cabal
  services/galley/migrate-data/src/Run.hs
  tools/db/migrate-features/.ormolu
  tools/db/migrate-features/README.md
  tools/db/migrate-features/default.nix
  tools/db/migrate-features/migrate-features.cabal
  tools/db/migrate-features/src/Main.hs
  tools/db/migrate-features/src/Options.hs
  tools/db/migrate-features/src/Work.hs
Labels: ok-to-test

#4475 Fix regex escaping in cassandra dump script
  hack/bin/cassandra_dump_schema
Labels: ok-to-test

#4477 WPB-16333 Fix: Prevent team creation by guests
  changelog.d/3-bug-fixes/WPB-16333
  integration/test/SetupHelpers.hs
  integration/test/Test/Teams.hs
  services/brig/src/Brig/API/User.hs
Labels: ok-to-test
